config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'gyms#index'
  resources :users, only: [:show]
  get "gyms/chibacity"
  
  resources :gyms
  post "contacts/thanks"
  resources :contacts, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  with_options presence: true do
    validates :email, format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
    validates :message
  end
end

app/models/gym.rb
class Gym < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  with_options presence: true do
    validates :name
    validates :image
    validates :address
    validates :playweek
    validates :playtime
    validates :map_url
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, uniqueness: true
  validates :password, confirmation: true, format: { with: /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?\d)[a-zA-Z\d]{6,32}+\z/i}
  with_options presence: true do
    validates :password_confirmation   
    validates :name, length: { maximum: 40 }
  end

  has_many :gyms
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_in)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
    render :action => 'new'
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.valid?
      render :action => 'create'
    else
      render :new
    end
  end

  def thanks
    @contact = Contact.new(contact_params)
    ContactMailer.contact_mail(@contact).deliver
    render :action => 'thanks'
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :message)
  end
end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
  def index
  end

  def new
    @gyms = Gym.new
  end

  def create
    @gym = Gym.new(gym_params)
    if @gym.save
      redirect_to new_gym_path
    else
      render :new
    end
  end

  def edit
    @gym = Gym.find(params[:id])
  end

  def update
    @gym = Gym.find(params[:id])
    if @gym.update(gym_params)
      redirect_to gym_path(@gym.id)
    else
      render :edit
    end
  end

  def destroy
    @gym = Gym.find(params[:id])
    @gym.destroy
    redirect_to root_path
  end

  def show
    @gym = Gym.find(params[:id])
  end

  def chibacity
  end

  private

  def gym_params
    params.require(:gym).permit(:image, :name, :address, :phone_number, :playweek, :playtime, :court, :map_url, :homepage, :supplement).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/city/chiba.html.erb
<div class="chiba-prefecture">
  <script src="https://www.land.mlit.go.jp/webland/api/CitySearch?area=12"></script>
</div>

app/views/contacts/create.html.erb
<h3 class="contact_title">お問い合わせ確認</h3>

<%= form_with model: @contact, url: contacts_thanks_path, local: true do |f| %>
  <div class="form_text">
    <%= f.label :emailアドレス, class:"confirm_text" %>
    <%= f.hidden_field :email %>
    <%= @contact.email %>
  </div>
  <div class="form_text">
    <%= f.label :お問い合わせ内容, class:"confirm_text" %>
    <%= f.hidden_field :message %>
    <%= @contact.message %>
  </div>
  <div class="form_btn">
    <%= f.submit '送信', class:"send_btn"%>
  </div>  
<% end %>

app/views/contacts/new.html.erb
<h3 class="contact_title">お問い合わせ</h3>

<%= form_with model: @contact, url: contacts_path, class: "form_contact", local: true do |f| %>
<%= render "shared/error_messages", model: f.object %>
  <div class="form_text">
    <%= f.label :emailアドレス %>
    <%= f.text_field :email, class:"email_text" %>
  </div>
  <div class="form_text">
    <%= f.label :お問い合わせ内容 %>
    <%= f.text_area :message, class:"message_area" %>
  </div>
  <div class="form_btn">
    <%= f.submit "確認", class:"send_btn"%>
    <%= link_to 'もどる', root_path, class:"return_top" %>
  </div>
<% end %>

app/views/contacts/thanks.html.erb
<h3 class="contact_title">お問い合わせ送信しました</h3>
<p class="thanks_text">お問い合わせいただきありがとうございました</p>
<div class="form_btn">
  <%= link_to "トップページへ戻る", root_path, class:"return_top"%>
</div>

app/views/gyms/chibacity.html.erb
<div class="main-city">
  <%= render "shared/header" %>
  <p>千葉県・市から施設を探す</p>
  <ul class="city_list">
    <p>あ行</p>
    <a href="">旭市</a>
    <ul>
      <li>個人開放の施設はありません</li>
    </ul>
    <a href="">我孫子市</a>
    <ul>
      <li>
        <%= link_to "我孫子市民体育館", "/gyms/1" %>
      </li>
    </ul>
    <a href="">市川市</a>
    <ul>
      <li>
        <%= link_to "信篤市民体育館", "/gyms/2"%>
      </li>
      <li>
        <%= link_to "塩浜市民体育館", "/gyms/3"%>
      </li>
      <li>
        <%= link_to "国府台市民体育館", "/gyms/4"%>
      </li>
    </ul>
    <a href="">市原市</a>
    <ul>
      <li>
        <%= link_to "ちはら台コミュニティセンター", "/gyms/5"%>
      </li>
    </ul>
    <a href="">印西市</a>
    <ul>
      <li>
        <%= link_to "松山下公園総合体育館", "/gyms/6"%>
      </li>
    </ul>
    <a href="">いすみ市</a>
    <ul>
      <li>
        <%= link_to "いすみ市Ｂ＆Ｇ海洋センター", "/gyms/7"%>
      </li>
    </ul>
    <a href="">浦安市</a>
    <ul>
      <li>
        <%= link_to "バルドラール浦安アリーナ(浦安市総合体育館)", "/gyms/8"%>
      </li>
    </ul>
    <a href="">大網白里市</a>
    <ul>
    </ul>
    <p>か行</p>
    <a href="">香取市</a>
    <ul>
    </ul>
    <a href="">柏市</a>
    <ul>
    </ul>
    <a href="">勝浦市</a>
    <ul>
    </ul>
    <a href="">鎌ヶ谷市</a>
    <ul>
    </ul>
    <a href="">鴨川市</a>
    <ul>
    </ul>
    <a href="">木更津市</a>
    <ul>
    </ul>
    <a href="">君津市</a>
    <ul>
    </ul>
    <p>さ行</p>
    <a href="">佐倉市</a>
    <ul>
    </ul>
    <a href="">山武市</a>
    <ul>
    </ul>
    <a href="">白井市</a>
    <ul>
    </ul>
    <a href="">匝瑳市</a>
    <ul>
    </ul>
    <a href="">袖ケ浦市</a>
    <ul>
    </ul>
    <p>た行</p>
    <a href="">館山市</a>
    <ul>
    </ul>
    <a href="">千葉市稲毛区</a>
    <ul>
    </ul>
    <a href="">千葉市中央区</a>
    <ul>
    </ul>
    <a href="">千葉市花見川区</a>
    <ul>
    </ul>
    <a href="">千葉市緑区</a>
    <ul>
    </ul>
    <a href="">千葉市美浜区</a>
    <ul>
    </ul>
    <a href="">千葉市若葉区</a>
    <ul>
    </ul>
    <a href="">銚子市</a>
    <ul>
    </ul>
    <a href="">東金市</a>
    <ul>
    </ul>
    <a href="">富里市</a>
    <ul>
    </ul>
    <p>な行</p>
    <a href="">流山市</a>
    <ul>
    </ul>
    <a href="">習志野市</a>
    <ul>
    </ul>
    <a href="">成田市</a>
    <ul>
    </ul>
    <a href="">野田市</a>
    <ul>
    </ul>
    <p>は行</p>
    <a href="">富津市</a>
    <ul>
    </ul>
    <a href="">船橋市</a>
    <ul>
    </ul>
    <p>ま行</p>
    <a href="">松戸市</a>
    <ul>
    </ul>
    <a href="">南房総市</a>
    <ul>
    </ul>
    <a href="">茂原市</a>
    <ul>
    </ul>
    <p>や行</p>
    <a href="">八街市</a>
    <ul>
    </ul>
    <a href="">八千代市</a>
    <ul>
    </ul>
    <a href="">四街道市</a>
    <ul>
    </ul>
  </ul>
</div>

app/views/gyms/edit.html.erb
<div class="add-gym-main">
  <p>バドミントン施設の情報を編集する</p>
  <%= form_with model: @gym do |f| %>

  <%= render "shared/error_messages", model: f.object %>

  <div class="img-up">
    <p>施設画像をアップロード</p>
    <%= f.file_field :image %>
  </div>
  <div class="new-gym">
    <p>施設名</p>
    <%= f.text_area :name, class:"gym-detail" %>
    <p>施設の住所</p>
    <%= f.text_area :address, class:"gym-detail"%>
    <p>施設の電話番号</p>
    <%= f.text_area :phone_number, class:"gym-detail"%>
    <p>施設の使える曜日</p>
    <%= f.text_area :playweek, class:"gym-detail"%>
    <p>施設の使える日時</p>
    <%= f.text_area :playtime, class:"gym-detail"%>
    <p>使えるコート数</p>
    <%= f.text_area :court, class:"gym-detail"%>
    <p>施設のホームページURL</p>
    <%= f.text_area :homepage, class:"gym-detail"%>
    <p>施設のgoogleマップURL</p>
    <%= f.text_area :map_url, class:"gym-detail"%>
    <p>補足情報</p>
    <%= f.text_area :supplement, class:"gym-detail"%>
  </div>

  <div class="gym-btn-contents">
    <%= f.submit "登録する", class: "gym-btn" %>
    <%= link_to 'トップページに戻る', root_path, class: "back-btn" %>
  </div>
  <% end %>
</div>

app/views/gyms/index.html.erb
<%= render "shared/header"%>

<div class="top-image">
  <img src="/assets/topbado.jpg" class="top-badoimage">
</div>

<%= render "shared/sessionbar"%>

<p class="top-overview">
  　Let's play badmintonは、全国の体育館やコミュニティセンターなど、バドミントンができる施設を検索できるサイトです。
</p>

<div class="search-menu">
  <p class="menu_rural_title">施設を探す</p>
  <p class="top-supplement">※現在、「関東・千葉」のみ検索可能</p>
  <ul class="menu_rural">
    <li>
      <a href="" class="parent_menu">北海道・東北</a>
      <ul>
        <li>
          <%= link_to "北海道", "#"%>
        <li>
          <%= link_to "青森", "#", class: "kanto" %>
        </li>
        <li>
          <%= link_to "秋田", "#", class:"kanto" %>
        </li>
        <li>
          <%= link_to "岩手", "#", class:"kanto" %>
        </li>
        <li>
          <%= link_to "山形", "#", class:"kanto" %>
        </li>
        <li>
          <%= link_to "宮城", "#", class: "kanto" %>
        </li>
        <li>
          <%= link_to "福島", "#", class: "kanto" %>
        </li>
      </ul>
    </li>

    <li>
      <a href="" class="parent_menu">関東</a>
      <ul>
        <li>
          <%= link_to "東京", "#", class:"kanto" %>
        </li>
        <li>
          <a href="gyms/chibacity">千葉</a>
        </li>
        <li>
          <%= link_to "埼玉", "#", class:"kanto" %>
        </li>
        <li>
          <%= link_to "茨城", "#", class: "kanto" %>
        </li>
        <li>
          <%= link_to "栃木", "#", class: "kanto" %>
        </li>
        <li>
          <%= link_to "群馬", "#", class: "kanto" %>
        </li>
        <li>
          <%= link_to "神奈川", "#", class: "kanto" %>
        </li>
      </ul>
    <li>

    <li>
      <a href="" class="parent_menu">中部</a>
      <ul>
        <li>
          <%= link_to "山梨", "#", class:"kanto" %>
        </li>
        <li>
          <%= link_to "長野", "#", class:"kanto" %>
        </li>
        <li>
          <%= link_to "新潟", "#", class:"kanto" %>
        </li>
        <li>
          <%= link_to "静岡", "#", class: "kanto" %>
        </li>
        <li>
          <%= link_to "愛知", "#", class: "kanto" %>
        </li>
        <li>
          <%= link_to "岐阜", "#", class: "kanto" %>
        </li>
        <li>
          <%= link_to "福井", "#", class: "kanto" %>
        </li>
        <li>
          <%= link_to "富山", "#", class: "kanto" %>
        </li>
        <li>
          <%= link_to "石川", "#", class: "kanto" %>
        </li>
      </ul>
    </li>

    <li>
      <a href="" class="parent_menu">近畿</a>
      <ul>
        <li>
          <%= link_to "滋賀", "#", class:"kanto" %>
        </li>
        <li>
          <%= link_to "三重", "#", class:"kanto" %>
        </li>
        <li>
          <%= link_to "京都", "#", class:"kanto" %>
        </li>
        <li>
          <%= link_to "奈良", "#", class: "kanto" %>
        </li>
        <li>
          <%= link_to "大阪", "#", class: "kanto" %>
        </li>
        <li>
          <%= link_to "和歌山", "#", class: "kanto" %>
        </li>
        <li>
          <%= link_to "兵庫", "#", class: "kanto" %>
        </li>
      </ul>
    </li>

    <li>
      <a href="" class="parent_menu">中国</a>
      <ul>
        <li>
          <%= link_to "鳥取", "#", class:"kanto" %>
        </li>
        <li>
          <%= link_to "岡山", "#", class:"kanto" %>
        </li>
        <li>
          <%= link_to "島根", "#", class:"kanto" %>
        </li>
        <li>
          <%= link_to "広島", "#", class: "kanto" %>
        </li>
        <li>
          <%= link_to "山口", "#", class: "kanto" %>
        </li>
      </ul>
    </li>

    <li>
      <a href="" class="parent_menu">四国</a>
      <ul>
        <li>
          <%= link_to "香川", "#", class:"kanto" %>
        </li>
        <li>
          <%= link_to "徳島", "#", class:"kanto" %>
        </li>
        <li>
          <%= link_to "愛媛", "#", class:"kanto" %>
        </li>
        <li>
          <%= link_to "高知", "#", class: "kanto" %>
        </li>
      </ul>
    </li>

    <li>
      <a href="" class="parent_menu">九州・沖縄</a>
      <ul>
        <li>
          <%= link_to "福岡", "#", class:"kanto" %>
        </li>
        <li>
          <%= link_to "佐賀", "#", class:"kanto" %>
        </li>
        <li>
          <%= link_to "長崎", "#", class:"kanto" %>
        </li>
        <li>
          <%= link_to "大分", "#", class: "kanto" %>
        </li>
        <li>
          <%= link_to "熊本", "#", class: "kanto" %>
        </li>
        <li>
          <%= link_to "宮崎", "#", class: "kanto" %>
        </li>
        <li>
          <%= link_to "鹿児島", "#", class: "kanto" %>
        </li>
        <li>
          <%= link_to "沖縄", "#", class: "kanto" %>
        </li>
      </ul>
    </li>
  </ul>
    

app/views/gyms/new.html.erb
<div class="add-gym-main">
  <h2>バドミントン施設の情報を入力</h2>
  <%= form_with model: @gyms, url: gyms_path, method: :post, scope: :gym do |f| %>

    <%#= render "shared/error_messages", model: f.object %>

  <div class="img-up">
    <p>施設画像をアップロード</p>
    <%= f.file_field :image %>
  </div>
  <div class="new-gym">
    <p>施設名(必須)</p>
    <%= f.text_area :name, class:"gym-detail" %>
    <p>施設の住所(必須)</p>
    <%= f.text_area :address, class:"gym-detail"%>
    <p>施設の電話番号</p>
    <%= f.text_area :phone_number, class:"gym-detail"%>
    <p>施設の使える曜日(必須)</p>
    <%= f.text_area :playweek, class:"gym-detail"%>
    <p>施設の使える日時(必須)</p>
    <%= f.text_area :playtime, class:"gym-detail"%>
    <p>使えるコート数(必須)</p>
    <%= f.text_area :court, class:"gym-detail"%>
    <p>施設のホームページURL</p>
    <%= f.text_area :homepage, class:"gym-detail"%>
    <p>施設のgoogleマップURL(必須)</p>
    <%= f.text_area :map_url, class:"gym-detail"%>
    <p>補足情報</p>
    <%= f.text_area :supplement, class:"gym-detail"%>
  </div>

  <div class="gym-btn-contents">
    <%= f.submit "登録する", class: "gym-btn" %>
    <%= link_to 'トップページに戻る', root_path, class: "back-btn" %>
  </div>
  <% end %>
</div>

app/views/gyms/show.html.erb
<%= render "shared/header" %>
<div class="show-content">
  <div class="gym_wrapper">
    <p class="gym-name">
      <%= @gym.name %>
    </p>
    <div class="gym-image">
      <%= image_tag @gym.image.variant(resize: '800x400') %>
    </div>
    <div class="gym-body">
      <div class="gym-detail">
        <b class="detail-title">電話番号</b>
        <p><%= @gym.phone_number %></p>
      </div>
      <div class="gym-detail">
        <b class="detail-title">住所</b>
        <p><%= @gym.address %></p>
      </div>
      <div class="gym-detail">
        <b class="detail-title">開館日</b>
        <p><%= @gym.playweek %></p>
        <b class="detail-title">開館時間</b>
        <p><%= @gym.playtime %></p>
      </div>
      <div class="gym-detail">
        <b class="detail-title">コート数</b>
        <p><%= @gym.court %></p>
      </div>
      <div class="gym-detail">
        <b class="detail-title">マップ</b>
        <p class="facility-page"><%= link_to "▶︎ #{@gym.name}のマップへ", @gym.map_url %></p>
      </div>
      <div class="gym-detail">
        <b class="detail-title">ホームページ</b>
        <p class="facility-page"><%= link_to "▶︎ #{@gym.name}のホームページへ", @gym.homepage %></p>
      </div>
      <div class="gym-detail">
        <b class="detail-title">補足</b>
        <p class="gym-supplement"><%= @gym.supplement %></p>
      </div>
    </div>
  </div>
  <% if user_signed_in? && current_user.admin? %>
    <%= link_to '施設の編集', edit_gym_path, method: :get, class: "gym-edit" %>
    <%= link_to '施設の削除', gym_path(@gym.id), method: :delete, class:'gym-destroy' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Let's play badminton</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <footer>
      <a href="" class="search_facility">施設検索</a>
      <a href="/contacts/new" class="question">お問い合わせ</a>
      <% if user_signed_in? && current_user.admin? %>
        <%= link_to "管理者専用ページ", new_gym_path, class:"admin-page" %>
      <% end %>
      <p class="app_name">gym-clairvoyant.2020</p>
    </footer>
  </body>

  
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header>
  <div class="header-bar">
    <a href="/" class="logo">Let's play badminton</a>
    <nav>
      <ul>
        <li><%= link_to "施設検索"%></li>
        <li><%= link_to "お問い合わせ", new_contact_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/shared/_sessionbar.html.erb
<div class="page-header">
  <div class="signin-bar">
    <ul class='right-bar'>
      <% if user_signed_in? %>
        <li><%= link_to current_user.name, user_path(current_user.id), class: "name" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<div class="mypage">
  <h2 class="mypage_heading">
    <%= "#{current_user.name}さんのページ" %>
  </h2>
  <table>
  <tr>
    <th>email</th>
    <td><%= current_user.email %></td>
  </tr>
  <tr>
    <th>お気に入り</th>
    <td>1940年</td>
  </tr>
</table>
</div>